services:
#    cms_common.example:
#        class: Stallfish\CmsCommonBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  stallfish.show.messages:
      class: Stallfish\CmsCommonBundle\Service\ShowMessageService
      arguments:
          - '@twig'
          - '@translator'

  stallfish.settings.parser:
      class: Stallfish\CmsCommonBundle\Service\SettingsParserService
      arguments:
          - '@filesystem'
          - '%kernel.root_dir%'

  stallfish.setting.aggregate:
      class: Stallfish\CmsCommonBundle\Service\SettingAggregateService
      arguments:
          - '@doctrine.orm.entity_manager'
          - '@stallfish.settings.parser'

  stallfish.settings:
    class: Stallfish\CmsCommonBundle\Service\SettingsService
    arguments:
        - '@stallfish.setting.aggregate'

  stallfish.settings.twig:
    class: Stallfish\CmsCommonBundle\Settings\Twig\StallfishSettingsExtension
    public: false
    arguments:
        - '@stallfish.settings'
    tags:
        - { name: twig.extension }

  stalfish.setting.validator:
    class: Stallfish\CmsCommonBundle\Service\SettingValidatorService