services:
#    cms_common.example:
#        class: Stallfish\CmsCommonBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  stallfish.show.messages:
      class: Stallfish\CmsCommonBundle\Service\ShowMessageService
      arguments:
          - '@twig'
          - '@translator'