<?php

namespace Stallfish\CmsCommonBundle\Repository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends \Doctrine\ORM\EntityRepository
{
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        return $this->findOneBy(['settingLabel' => $id]);
    }
}
